from app.api.exceptions.exceptions import (
    unauthorized_exception,
    credentials_exception,
    doctor_not_found,
    patient_not_found,
    bad_date_formatting,
    bed_not_found,
    patient_already_hospitalized,
    bed_already_used,
    room_already_with_bed,
    speciality_not_found,
    speciality_doctor_not_found,
    speciality_doctor_found,
    create_speciality,
    patient_cannot_be_his_responsable,
    patient_cannot_be_responsable,
    patient_doctor_same_document,
    responsable_not_found,
    responsable_found,
    user_not_found,
    non_superuser,
    num_document_used,
    user_found,
    patient_in_bed,
    invalid_email,
    existent_phone,
    failed_to_save_historial,
    failed_to_save_file,
    failed_to_delete_file,
    failed_to_found_file,
    file_extention_not_allowed,
)
